#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "David Afonso"
email = "david.afonso@paypay-corp.co.jp"

[aliases]
push = ["util", "exec", "--", "uvx", "jj-pre-push", "push"]

[ui]
default-command = "log"
